name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: linux
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore Tests -p:Configuration=Release

      - name: Run tests
        run: dotnet test Tests -c Release --no-restore
