name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Authenticate to GitHub Packages
        run: dotnet nuget add source --username resnyanskiy --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/resnyanskiy/index.json"
          
      - name: Restore dependencies
        run: dotnet restore Tests -p:Configuration=Release

      - name: Run tests
        run: dotnet test Tests -c Release --no-restore
